### ISSUE TITLE
Tag v1.0.1 is outdated and contains a bug, fixed in main branch

### ISSUE THREAD

**Issue by dranovsk** [enhance-dev/enhance-element#1]
Tag v1.0.1 is outdated and contains a bug, fixed in main branch

***main branch***
https://github.com/enhance-dev/enhance-element/blob/5e3a95881441eeeec0caa5750474708b0b718945/index.mjs#L51

***v1.0.1***
https://github.com/enhance-dev/enhance-element/blob/1acd139f586aa849629130fc27ddc35edba72910/index.mjs#L51

**Comment by macdonst** [comment]
We released v1.0.2 to fix this issue.
