### ISSUE TITLE
Element styles are not hoisted + scoped/deduped

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/enhance-element#10]
When rendering multiple instances of an SFC on the client via Enhance Element, the element's styles are not deduped or hoisted & scoped. Instead, each instance of the element is rendered with a duplicate `<style>` block, where the contained styles are not scoped to the element.

One option could be to simply strip the element's `<style>` block (if present), however this would preclude using Enhance Element for a strictly client side element with styles.

Another option could (maybe?) be to check for an existing style block and only strip it from the client instance(s) if one is present in the document head.

Further discussion likely required but wanted to flag this early! :)

Discussion re: an example of this + a link to a temporary fix can be found in the issue mentioned below.

**Comment by kristoferjoseph** [comment]
Yes this is a known issue. There needs to be an HTML function for use in the browser that mimics the behavior of Enhance SSR but uses the DOM APIs instead.

I wasn't sure we wanted to go this far.

**Comment by colepeters** [comment]
@kristoferjoseph Get back to your vacation, sir! 😉 ❤️

**Comment by macdonst** [comment]
One possible solution I had success with today is to pass in an option to drop the styles on the client since they were already hoisted into the head.

https://github.com/enhance-dev/enhance-element/commit/12c54be52789c0a121dd9e194fb582fddf755061

**Comment by kristoferjoseph** [comment]
The issue is that if your component uses the shadow DOM then you need the style block to remain.

**Comment by macdonst** [comment]
Yup, that's why I made it an option to strip the styles. If you've written your component without the shadow DOM then it would be safe to strip the style tag as it is already included in the head tag.
